name: CI
on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/*.md"
  push:
    branches: [main, master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NXF_ANSI_LOG: false

jobs:
  nf-test:
    name: nf-test | docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "25.04.0"

      - name: Install nf-test
        uses: nf-core/setup-nf-test@v1
        with:
          version: "0.9.3"

      - name: Run nf-test
        run: nf-test test tests/default.nf.test --profile +docker --verbose

  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files
